/**
 * MockupProject (`.mockupproject`) <-> Y.Doc binding.
 *
 * Pattern A from the collaboration guide: keyed entities. The Y.Doc carries
 * three top-level shared types -- `mockups` and `connections` as Y.Map<id,
 * Y.Map<fields>>, plus a `meta` Y.Map for project-level scalar state. The
 * local source of truth at edit time is still the Zustand store from
 * `createMockupProjectStore`; the binding mirrors store mutations to the
 * Y.Doc and vice versa.
 *
 * Local store -> Y.Doc:
 *   The binding subscribes to the Zustand store. On every notification it
 *   diffs the current store state against `lastKnownProject` and emits the
 *   minimum set of Y.Map writes that closes the gap. Per-field writes mean
 *   two clients editing different fields on the same mockup converge
 *   without clobbering each other.
 *
 * Y.Doc -> local store:
 *   `observeDeep` on each Y.Map fires when remote (or local) writes land.
 *   For every fired event we project Y.Doc back to a `MockupProjectFile`
 *   and call `store.loadFromFile(...)`. The store's `applyingRemote` flag
 *   is set first so the subscribe-side handler ignores the resulting tick.
 *
 * Awareness:
 *   The host pre-populates `user`. The binding mirrors the store's
 *   `selectedMockupId` / `selectedConnectionId` into awareness so other
 *   clients can render presence overlays for "X is looking at screen Y".
 *
 * Undo/redo:
 *   `Y.UndoManager` only tracks operations tagged with our binding origin,
 *   so undo doesn't step on a teammate's edits. In local-only mode the
 *   store keeps its own (currently absent) undo stack; the manager is only
 *   instantiated when `host.collaboration` is defined.
 *
 * Bootstrap-race safety:
 *   Mockup and connection ids are content-derived (assigned in the file
 *   itself, never re-generated by the seed). Two clients seeding the same
 *   file write identical `(id -> fields)` pairs and Y.Map's last-write-
 *   wins-per-key merge collapses to either client's individual shape.
 */

import * as Y from 'yjs';
import type * as awarenessProtocol from 'y-protocols/awareness';
import { COLLAB_INIT_ORIGIN } from '@nimbalyst/extension-sdk';
import type {
  Connection,
  MockupProjectFile,
  MockupReference,
} from '../types/project';
import type { MockupProjectStoreApi } from '../store/projectStore';
import {
  PROJECT_SCHEMA_VERSION,
  getYProjectConnections,
  getYProjectMeta,
  getYProjectMockups,
  readProjectFromYDoc,
  writeConnectionFields,
  writeMockupFields,
} from './seed';

export interface MockupProjectBindingOptions {
  /**
   * Optional hook for presence indicators on remote awareness change. The
   * editor itself reads `host.collaboration.awareness` to render overlays;
   * this is a convenience so the binding consumer can trigger React updates.
   */
  onRemoteAwareness?: () => void;
  /**
   * If false (default), the binding does NOT hijack undo/redo. Pass true
   * to instantiate a `Y.UndoManager` tracked to this binding's origin so
   * undo only touches local ops.
   */
  enableUndoManager?: boolean;
}

export class MockupProjectBinding {
  private yDoc: Y.Doc;
  private yMockups: Y.Map<Y.Map<unknown>>;
  private yConnections: Y.Map<Y.Map<unknown>>;
  private yMeta: Y.Map<unknown>;
  private store: MockupProjectStoreApi;
  private awareness?: awarenessProtocol.Awareness;
  private opts: MockupProjectBindingOptions;

  /** Y.UndoManager hijack -- only created in collab mode. */
  public readonly undoManager?: Y.UndoManager;

  private subscriptions: Array<() => void> = [];
  private destroyed = false;
  /** True while we're projecting Y.Doc state into the store; suppresses the
   * store->Y.Doc path in that window. */
  private applyingRemote = false;

  /** Snapshot of the store state we last reflected into Y.Doc, used as the
   * baseline for the diff. Keyed by mockup/connection id for O(1) lookups. */
  private lastKnownMockups = new Map<string, MockupReference>();
  private lastKnownConnections = new Map<string, Connection>();
  private lastKnownMetaName = '';
  private lastKnownMetaDescription = '';
  private lastKnownDesignSystemJson: string | undefined = undefined;
  private lastKnownViewport = { x: 0, y: 0, zoom: 1 };
  private lastKnownSelection = {
    mockupId: null as string | null,
    connectionId: null as string | null,
  };

  constructor(
    yDoc: Y.Doc,
    store: MockupProjectStoreApi,
    opts: MockupProjectBindingOptions = {},
    awareness?: awarenessProtocol.Awareness,
  ) {
    this.yDoc = yDoc;
    this.yMockups = getYProjectMockups(yDoc);
    this.yConnections = getYProjectConnections(yDoc);
    this.yMeta = getYProjectMeta(yDoc);
    this.store = store;
    this.awareness = awareness;
    this.opts = opts;

    // -------- Initial projection: Y.Doc -> store --------
    // Project whatever the Y.Doc currently has (seed contents, or content
    // synced from a remote client) into the store BEFORE we wire the local
    // observer. This way the very first store-subscribe notification we get
    // already has the Y.Doc state reflected, and our `lastKnown*` snapshots
    // are accurate so no spurious writes are emitted.
    this.projectYDocToStore();
    this.captureLastKnownFromStore();

    // -------- Store -> Y.Doc --------
    const unsubscribeStore = this.store.subscribe(() => {
      if (this.destroyed) return;
      if (this.applyingRemote) return;
      this.flushStoreToYDoc();
      this.flushSelectionToAwareness();
    });
    this.subscriptions.push(unsubscribeStore);

    // -------- Y.Doc -> store --------
    const applyRemote = (txn: Y.Transaction): void => {
      if (this.destroyed) return;
      // Ignore echoes of our own writes (transaction origin === this binding).
      if (txn.origin === this) return;
      // Ignore SDK seed transactions -- the store was loaded from the file
      // earlier in the lifecycle path; reapplying would just thrash.
      if (txn.origin === COLLAB_INIT_ORIGIN) return;
      this.applyingRemote = true;
      try {
        this.projectYDocToStore();
        this.captureLastKnownFromStore();
      } finally {
        this.applyingRemote = false;
      }
    };
    const onMockupsRemote = (
      _events: Array<Y.YEvent<Y.AbstractType<unknown>>>,
      txn: Y.Transaction,
    ): void => applyRemote(txn);
    const onConnectionsRemote = (
      _events: Array<Y.YEvent<Y.AbstractType<unknown>>>,
      txn: Y.Transaction,
    ): void => applyRemote(txn);
    const onMetaRemote = (
      _event: Y.YMapEvent<unknown>,
      txn: Y.Transaction,
    ): void => applyRemote(txn);
    this.yMockups.observeDeep(onMockupsRemote);
    this.yConnections.observeDeep(onConnectionsRemote);
    this.yMeta.observe(onMetaRemote);
    this.subscriptions.push(() => this.yMockups.unobserveDeep(onMockupsRemote));
    this.subscriptions.push(() => this.yConnections.unobserveDeep(onConnectionsRemote));
    this.subscriptions.push(() => this.yMeta.unobserve(onMetaRemote));

    // -------- Awareness --------
    if (this.awareness) {
      const onAwareness = () => this.opts.onRemoteAwareness?.();
      this.awareness.on('change', onAwareness);
      this.subscriptions.push(() => this.awareness?.off('change', onAwareness));
      // Publish initial selection so remote clients see us immediately.
      this.flushSelectionToAwareness();
    }

    // -------- Undo manager --------
    if (opts.enableUndoManager) {
      this.undoManager = new Y.UndoManager(
        [this.yMockups, this.yConnections, this.yMeta],
        { trackedOrigins: new Set([this]) },
      );
      this.subscriptions.push(() => this.undoManager?.destroy());
    }
  }

  destroy(): void {
    if (this.destroyed) return;
    this.destroyed = true;
    for (const s of this.subscriptions) {
      try {
        s();
      } catch {
        /* ignore */
      }
    }
    this.subscriptions = [];
  }

  /** Manually undo through the bound Y.UndoManager, if collab is enabled. */
  undo(): void {
    this.undoManager?.undo();
  }

  /** Manually redo through the bound Y.UndoManager, if collab is enabled. */
  redo(): void {
    this.undoManager?.redo();
  }

  // ===================================================================
  // store <-> Y.Doc plumbing
  // ===================================================================

  private flushStoreToYDoc(): void {
    const state = this.store.getState();

    const mockupsById = new Map<string, MockupReference>(
      state.mockups.map((m) => [m.id, m]),
    );
    const connectionsById = new Map<string, Connection>(
      state.connections.map((c) => [c.id, c]),
    );

    let metaChanged = false;
    const metaName = state.name ?? '';
    const metaDescription = state.description ?? '';
    const designSystemJson = state.designSystem
      ? JSON.stringify(state.designSystem)
      : undefined;
    const viewport = state.viewport ?? { x: 0, y: 0, zoom: 1 };
    if (
      metaName !== this.lastKnownMetaName ||
      metaDescription !== this.lastKnownMetaDescription ||
      designSystemJson !== this.lastKnownDesignSystemJson ||
      viewport.x !== this.lastKnownViewport.x ||
      viewport.y !== this.lastKnownViewport.y ||
      viewport.zoom !== this.lastKnownViewport.zoom
    ) {
      metaChanged = true;
    }

    // Diff mockups
    const mockupAdds: MockupReference[] = [];
    const mockupUpdates: MockupReference[] = [];
    const mockupDeletes: string[] = [];
    for (const [id, mockup] of mockupsById) {
      const prev = this.lastKnownMockups.get(id);
      if (!prev) {
        mockupAdds.push(mockup);
      } else if (!isMockupEqual(prev, mockup)) {
        mockupUpdates.push(mockup);
      }
    }
    for (const id of this.lastKnownMockups.keys()) {
      if (!mockupsById.has(id)) mockupDeletes.push(id);
    }

    // Diff connections
    const connAdds: Connection[] = [];
    const connUpdates: Connection[] = [];
    const connDeletes: string[] = [];
    for (const [id, conn] of connectionsById) {
      const prev = this.lastKnownConnections.get(id);
      if (!prev) {
        connAdds.push(conn);
      } else if (!isConnectionEqual(prev, conn)) {
        connUpdates.push(conn);
      }
    }
    for (const id of this.lastKnownConnections.keys()) {
      if (!connectionsById.has(id)) connDeletes.push(id);
    }

    const noOp =
      !metaChanged &&
      mockupAdds.length === 0 &&
      mockupUpdates.length === 0 &&
      mockupDeletes.length === 0 &&
      connAdds.length === 0 &&
      connUpdates.length === 0 &&
      connDeletes.length === 0;
    if (noOp) return;

    this.yDoc.transact(() => {
      for (const mockup of mockupAdds) {
        const yEntry = new Y.Map<unknown>();
        writeMockupFields(yEntry, mockup);
        this.yMockups.set(mockup.id, yEntry);
      }
      for (const mockup of mockupUpdates) {
        const yEntry = this.yMockups.get(mockup.id);
        if (yEntry) {
          writeMockupFields(yEntry, mockup);
        } else {
          // Race: remote deleted this id between our diff and apply.
          // Re-add it; the next remote tick will reconcile if needed.
          const recreated = new Y.Map<unknown>();
          writeMockupFields(recreated, mockup);
          this.yMockups.set(mockup.id, recreated);
        }
      }
      for (const id of mockupDeletes) {
        this.yMockups.delete(id);
      }
      for (const conn of connAdds) {
        const yEntry = new Y.Map<unknown>();
        writeConnectionFields(yEntry, conn);
        this.yConnections.set(conn.id, yEntry);
      }
      for (const conn of connUpdates) {
        const yEntry = this.yConnections.get(conn.id);
        if (yEntry) {
          writeConnectionFields(yEntry, conn);
        } else {
          const recreated = new Y.Map<unknown>();
          writeConnectionFields(recreated, conn);
          this.yConnections.set(conn.id, recreated);
        }
      }
      for (const id of connDeletes) {
        this.yConnections.delete(id);
      }
      if (metaChanged) {
        this.yMeta.set('version', PROJECT_SCHEMA_VERSION);
        this.yMeta.set('name', metaName);
        if (metaDescription) {
          this.yMeta.set('description', metaDescription);
        } else {
          this.yMeta.delete('description');
        }
        if (state.designSystem) {
          this.yMeta.set('designSystem', state.designSystem);
        } else {
          this.yMeta.delete('designSystem');
        }
        this.yMeta.set('viewportX', viewport.x);
        this.yMeta.set('viewportY', viewport.y);
        this.yMeta.set('viewportZoom', viewport.zoom);
      }
    }, this);

    // Update bookkeeping. Selection state is intentionally NOT captured
    // here -- flushSelectionToAwareness (called by the subscriber after
    // this) compares the current store selection against lastKnownSelection
    // to decide whether to publish, and updates the snapshot AFTER the
    // publish. Capturing here would race and silently suppress every
    // selection change after the first.
    this.lastKnownMockups = mockupsById;
    this.lastKnownConnections = connectionsById;
    this.lastKnownMetaName = metaName;
    this.lastKnownMetaDescription = metaDescription;
    this.lastKnownDesignSystemJson = designSystemJson;
    this.lastKnownViewport = { ...viewport };
  }

  private projectYDocToStore(): void {
    const file = readProjectFromYDoc(this.yDoc) as MockupProjectFile;
    const state = this.store.getState();
    // Preserve current selection across remote-driven reloads -- the store's
    // loadFromFile clears selection by design (suitable for fresh open), so
    // we restore it on the next tick. We don't try to validate that the id
    // still exists; if not, the next subscribe tick will reflect that.
    const prevMockupSel = state.selectedMockupId;
    const prevConnectionSel = state.selectedConnectionId;
    state.loadFromFile(file);
    // markInitialLoadComplete: loadFromFile resets to false on every call,
    // but in collab mode every remote update would re-trigger the
    // "viewport drift" guard. Mark immediately so subsequent local viewport
    // changes from the user still propagate.
    state.markInitialLoadComplete();
    if (prevMockupSel || prevConnectionSel) {
      const exists = (id: string | null): boolean =>
        !!id && file.mockups.some((m) => m.id === id);
      const connectionExists = (id: string | null): boolean =>
        !!id && file.connections.some((c) => c.id === id);
      this.store.setState({
        selectedMockupId: exists(prevMockupSel) ? prevMockupSel : null,
        selectedConnectionId: connectionExists(prevConnectionSel)
          ? prevConnectionSel
          : null,
      });
    }
  }

  private captureLastKnownFromStore(): void {
    const state = this.store.getState();
    this.lastKnownMockups = new Map(state.mockups.map((m) => [m.id, m]));
    this.lastKnownConnections = new Map(
      state.connections.map((c) => [c.id, c]),
    );
    this.lastKnownMetaName = state.name ?? '';
    this.lastKnownMetaDescription = state.description ?? '';
    this.lastKnownDesignSystemJson = state.designSystem
      ? JSON.stringify(state.designSystem)
      : undefined;
    this.lastKnownViewport = { ...state.viewport };
    this.lastKnownSelection.mockupId = state.selectedMockupId;
    this.lastKnownSelection.connectionId = state.selectedConnectionId;
  }

  // ===================================================================
  // Awareness
  // ===================================================================

  private flushSelectionToAwareness(): void {
    if (!this.awareness) return;
    const state = this.store.getState();
    if (state.selectedMockupId !== this.lastKnownSelection.mockupId) {
      this.awareness.setLocalStateField(
        'selectedMockupId',
        state.selectedMockupId,
      );
      this.lastKnownSelection.mockupId = state.selectedMockupId;
    }
    if (state.selectedConnectionId !== this.lastKnownSelection.connectionId) {
      this.awareness.setLocalStateField(
        'selectedConnectionId',
        state.selectedConnectionId,
      );
      this.lastKnownSelection.connectionId = state.selectedConnectionId;
    }
  }
}

function isMockupEqual(a: MockupReference, b: MockupReference): boolean {
  return (
    a.path === b.path &&
    a.label === b.label &&
    a.position.x === b.position.x &&
    a.position.y === b.position.y &&
    a.size.width === b.size.width &&
    a.size.height === b.size.height
  );
}

function isConnectionEqual(a: Connection, b: Connection): boolean {
  return (
    a.fromMockupId === b.fromMockupId &&
    a.toMockupId === b.toMockupId &&
    a.fromElementSelector === b.fromElementSelector &&
    a.label === b.label &&
    a.trigger === b.trigger
  );
}
