package com.nimbalyst.app.crypto

import com.google.gson.Gson
import java.io.InputStreamReader
import java.nio.charset.StandardCharsets
import java.util.Base64
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Wire-compatibility test proving the Android [CryptoManager] is byte-for-byte
 * compatible with the iOS/desktop crypto, by running against the canonical iOS
 * test vectors.
 *
 * The vectors are copied byte-identically from
 * `packages/ios/CryptoCompatibility/test-vectors.json` into
 * `app/src/test/resources/crypto/test-vectors.json`. They are generated by
 * `packages/ios/CryptoCompatibility/generate-test-vectors.mjs` using the JS Web
 * Crypto API and are consumed unchanged by `CryptoCompatibilityTests.swift`.
 * If either side drifts (PBKDF2 params, AES-GCM wire format, fixed project_id
 * IV), this test fails.
 *
 * Wire format under test:
 *   - Key derivation: PBKDF2-HMAC-SHA256, 100k iterations, 256-bit output,
 *     salt = `nimbalyst:{userId}`.
 *   - Encryption: AES-256-GCM, IV = 12 bytes base64, ciphertext = base64 of
 *     (ciphertext || 16-byte auth tag).
 *   - project_id uses a fixed deterministic IV ("project_id_i").
 *
 * Pure-JVM: [CryptoManager] depends only on `java.security` / `javax.crypto` /
 * `java.util.Base64`, no Android framework APIs, so no Robolectric is needed.
 */
class CryptoWireCompatTest {

    // ---- Vector JSON shape (matches test-vectors.json exactly) -------------

    private data class TestVectors(
        val keyDerivation: KeyDerivation,
        val testCases: List<TestCase>,
    )

    private data class KeyDerivation(
        val passphrase: String,
        val salt: String,
        val iterations: Int,
        val hash: String,
        val keyLengthBits: Int,
        val derivedKeyBase64: String,
    )

    private data class TestCase(
        val name: String,
        val plaintext: String,
        val iv: String,
        val encrypted: String,
        val note: String? = null,
    )

    private fun loadVectors(): TestVectors {
        val stream = javaClass.getResourceAsStream("/crypto/test-vectors.json")
        assertNotNull("test-vectors.json must be on the test classpath at /crypto/test-vectors.json", stream)
        return InputStreamReader(stream!!, StandardCharsets.UTF_8).use { reader ->
            Gson().fromJson(reader, TestVectors::class.java)
        }
    }

    /**
     * The vector salt is the full derivation salt (`nimbalyst:{userId}`).
     * [CryptoManager.fromSeed] re-applies the `nimbalyst:` prefix, so strip it
     * to recover the userId.
     */
    private fun userIdFromSalt(salt: String): String {
        val prefix = "nimbalyst:"
        require(salt.startsWith(prefix)) { "Unexpected salt format: $salt" }
        return salt.removePrefix(prefix)
    }

    // ---- (a) PBKDF2 key-derivation parity ----------------------------------

    @Test
    fun `derived key matches canonical ios vector`() {
        val vectors = loadVectors()
        val kd = vectors.keyDerivation

        // Sanity-check the vector params match what CryptoManager implements.
        assertEquals(100_000, kd.iterations)
        assertEquals("SHA-256", kd.hash)
        assertEquals(256, kd.keyLengthBits)

        val keyBytes = CryptoManager.deriveKey(
            passphrase = kd.passphrase,
            salt = kd.salt,
        )

        assertEquals(
            kd.derivedKeyBase64,
            Base64.getEncoder().encodeToString(keyBytes),
        )
    }

    // ---- (b) Decrypt every vector case -------------------------------------

    @Test
    fun `decrypt all ios vector cases`() {
        val vectors = loadVectors()
        val userId = userIdFromSalt(vectors.keyDerivation.salt)
        val crypto = CryptoManager.fromSeed(
            seed = vectors.keyDerivation.passphrase,
            userId = userId,
        )

        for (case in vectors.testCases) {
            val decrypted = crypto.decrypt(
                encryptedBase64 = case.encrypted,
                ivBase64 = case.iv,
            )
            assertEquals(
                "Decryption mismatch for vector case '${case.name}'",
                case.plaintext,
                decrypted,
            )
        }
    }

    // ---- (c) Deterministic project_id encryption round-trip ----------------

    @Test
    fun `encryptProjectId reproduces deterministic ios ciphertext`() {
        val vectors = loadVectors()
        val userId = userIdFromSalt(vectors.keyDerivation.salt)
        val crypto = CryptoManager.fromSeed(
            seed = vectors.keyDerivation.passphrase,
            userId = userId,
        )

        val projectCase = vectors.testCases.first { it.name == "project_id_fixed_iv" }

        // The fixed-IV vector must use the project_id IV CryptoManager hardcodes.
        assertEquals(CryptoManager.projectIdIvBase64, projectCase.iv)

        assertEquals(
            "encryptProjectId must reproduce the deterministic iOS ciphertext",
            projectCase.encrypted,
            crypto.encryptProjectId(projectCase.plaintext),
        )
    }
}
